In [26]:
import numpy as np # linear algebra
import pandas as pd

In [27]:
df=pd.read_csv("/kaggle/input/jpx-tokyo-stock-exchange-prediction/supplemental_files/stock_prices.csv")
df.head()

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag,Target
0,20211206_1301,2021-12-06,1301,2982.0,2982.0,2965.0,2971.0,8900,1.0,NaN,False,-0.003263
1,20211206_1332,2021-12-06,1332,592.0,599.0,588.0,589.0,1360800,1.0,NaN,False,-0.008993
2,20211206_1333,2021-12-06,1333,2368.0,2388.0,2360.0,2377.0,125900,1.0,NaN,False,-0.009963
3,20211206_1375,2021-12-06,1375,1230.0,1239.0,1224.0,1224.0,81100,1.0,NaN,False,-0.015032
4,20211206_1376,2021-12-06,1376,1339.0,1372.0,1339.0,1351.0,6200,1.0,NaN,False,0.002867

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269881 entries, 0 to 269880
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   RowId             269881 non-null  object
 1   Date              269881 non-null  object
 2   SecuritiesCode    269881 non-null  int64
 3   Open              269063 non-null  float64
 4   High              269063 non-null  float64
 5   Low               269063 non-null  float64
 6   Close             269063 non-null  float64
 7   Volume            269881 non-null  int64
 8   AdjustmentFactor  269881 non-null  float64
 9   ExpectedDividend  2011 non-null    float64
 10  SupervisionFlag   269881 non-null  bool
 11  Target            269873 non-null  float64
dtypes: bool(1), float64(7), int64(2), object(2)
memory usage: 22.9+ MB

Date is treated as a object here instead you can parse use parse_dates

In [29]:
df=pd.read_csv("/kaggle/input/jpx-tokyo-stock-exchange-prediction/supplemental_files/stock_prices.csv",parse_dates=['Date'])
df.head()

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag,Target
0,20211206_1301,2021-12-06,1301,2982.0,2982.0,2965.0,2971.0,8900,1.0,NaN,False,-0.003263
1,20211206_1332,2021-12-06,1332,592.0,599.0,588.0,589.0,1360800,1.0,NaN,False,-0.008993
2,20211206_1333,2021-12-06,1333,2368.0,2388.0,2360.0,2377.0,125900,1.0,NaN,False,-0.009963
3,20211206_1375,2021-12-06,1375,1230.0,1239.0,1224.0,1224.0,81100,1.0,NaN,False,-0.015032
4,20211206_1376,2021-12-06,1376,1339.0,1372.0,1339.0,1351.0,6200,1.0,NaN,False,0.002867

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 269881 entries, 0 to 269880
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   RowId             269881 non-null  object
 1   Date              269881 non-null  datetime64[ns]
 2   SecuritiesCode    269881 non-null  int64
 3   Open              269063 non-null  float64
 4   High              269063 non-null  float64
 5   Low               269063 non-null  float64
 6   Close             269063 non-null  float64
 7   Volume            269881 non-null  int64
 8   AdjustmentFactor  269881 non-null  float64
 9   ExpectedDividend  2011 non-null    float64
 10  SupervisionFlag   269881 non-null  bool
 11  Target            269873 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(7), int64(2), object(1)
memory usage: 22.9+ MB

Open: First traded price on a day
High: Highest traded price on a day
Low : Lowest traded price on a day
Close: Last traded price on a day
Volume: 
AdjustmentFactor:
ExpectedDividend:
SupervisionFlag:
Target:

In [31]:
missing_rows = df[df['Open'].isnull()]
missing_rows

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag,Target
26,20211206_1723,2021-12-06,1723,NaN,NaN,NaN,NaN,0,1.0,NaN,False,0.001258
32,20211206_1787,2021-12-06,1787,NaN,NaN,NaN,NaN,0,1.0,NaN,False,-0.006590
716,20211206_4628,2021-12-06,4628,NaN,NaN,NaN,NaN,0,1.0,NaN,False,0.000000
848,20211206_5217,2021-12-06,5217,NaN,NaN,NaN,NaN,0,1.0,NaN,False,0.000000
922,20211206_5918,2021-12-06,5918,NaN,NaN,NaN,NaN,0,1.0,NaN,False,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
267985,20220624_1981,2022-06-24,1981,NaN,NaN,NaN,NaN,0,1.0,NaN,False,0.007634
268156,20220624_2814,2022-06-24,2814,NaN,NaN,NaN,NaN,0,1.0,NaN,False,0.000000
268599,20220624_4628,2022-06-24,4628,NaN,NaN,NaN,NaN,0,1.0,NaN,False,0.000000
268866,20220624_6144,2022-06-24,6144,NaN,NaN,NaN,NaN,0,1.0,NaN,False,0.040578
268985,20220624_6484,2022-06-24,6484,NaN,NaN,NaN,NaN,0,1.0,NaN,False,0.013667

In [32]:
# Remove such missing values
df_cleaned= df.dropna(subset=['Open'])
df_cleaned.head(30)

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag,Target
0,20211206_1301,2021-12-06,1301,2982.0,2982.0,2965.0,2971.0,8900,1.0,NaN,False,-0.003263
1,20211206_1332,2021-12-06,1332,592.0,599.0,588.0,589.0,1360800,1.0,NaN,False,-0.008993
2,20211206_1333,2021-12-06,1333,2368.0,2388.0,2360.0,2377.0,125900,1.0,NaN,False,-0.009963
3,20211206_1375,2021-12-06,1375,1230.0,1239.0,1224.0,1224.0,81100,1.0,NaN,False,-0.015032
4,20211206_1376,2021-12-06,1376,1339.0,1372.0,1339.0,1351.0,6200,1.0,NaN,False,0.002867
5,20211206_1377,2021-12-06,1377,3185.0,3215.0,3180.0,3200.0,77000,1.0,NaN,False,0.003044
6,20211206_1379,2021-12-06,1379,1890.0,1898.0,1885.0,1889.0,48500,1.0,NaN,False,-0.009870
7,20211206_1381,2021-12-06,1381,3200.0,3200.0,3150.0,3150.0,1600,1.0,NaN,False,0.000000
8,20211206_1407,2021-12-06,1407,6100.0,6290.0,6010.0,6220.0,246700,1.0,NaN,False,-0.004732
9,20211206_1413,2021-12-06,1413,2185.0,2211.0,2181.0,2190.0,9200,1.0,NaN,False,0.002222
10,20211206_1414,2021-12-06,1414,5090.0,5110.0,5040.0,5060.0,121500,1.0,NaN,False,-0.009728
11,20211206_1417,2021-12-06,1417,2001.0,2019.0,1988.0,1991.0,209200,1.0,NaN,False,-0.010386
12,20211206_1419,2021-12-06,1419,2285.0,2289.0,2253.0,2288.0,123500,1.0,NaN,False,-0.018684
13,20211206_1429,2021-12-06,1429,709.0,714.0,704.0,712.0,33300,1.0,NaN,False,-0.005355
14,20211206_1431,2021-12-06,1431,831.0,862.0,818.0,837.0,43700,1.0,NaN,False,-0.002312
15,20211206_1435,2021-12-06,1435,226.0,227.0,221.0,222.0,209700,1.0,NaN,False,0.008584
16,20211206_1515,2021-12-06,1515,6340.0,6360.0,6240.0,6310.0,12200,1.0,NaN,False,0.003120
17,20211206_1518,2021-12-06,1518,1355.0,1380.0,1331.0,1332.0,453800,1.0,NaN,False,0.016464
18,20211206_1605,2021-12-06,1605,937.0,956.0,937.0,947.0,9554500,1.0,NaN,False,0.015400
19,20211206_1662,2021-12-06,1662,2385.0,2412.0,2361.0,2397.0,292000,1.0,NaN,False,0.030000
20,20211206_1663,2021-12-06,1663,1482.0,1507.0,1456.0,1460.0,30500,1.0,NaN,False,-0.002694
21,20211206_1712,2021-12-06,1712,1663.0,1699.0,1621.0,1647.0,79300,1.0,NaN,False,0.021059
22,20211206_1716,2021-12-06,1716,1336.0,1336.0,1310.0,1312.0,7500,1.0,NaN,False,0.002999
23,20211206_1719,2021-12-06,1719,889.0,897.0,879.0,880.0,825600,1.0,NaN,False,-0.007848
24,20211206_1720,2021-12-06,1720,675.0,678.0,664.0,664.0,330800,1.0,NaN,False,-0.007396
25,20211206_1721,2021-12-06,1721,2520.0,2573.0,2519.0,2558.0,481200,1.0,NaN,False,-0.009150
27,20211206_1726,2021-12-06,1726,353.0,355.0,348.0,349.0,148300,1.0,NaN,False,-0.013736
28,20211206_1762,2021-12-06,1762,1945.0,1952.0,1938.0,1946.0,46200,1.0,NaN,False,-0.003035
29,20211206_1766,2021-12-06,1766,9290.0,9400.0,9160.0,9280.0,12900,1.0,NaN,False,0.004224
30,20211206_1775,2021-12-06,1775,2580.0,2614.0,2580.0,2612.0,700,1.0,NaN,False,0.023274

**Indexes are also removed along with the removed values, if reset_index function not given (Notice index 26)**

In [33]:
df_cleaned= df.dropna(subset=['Open']).reset_index(drop=True)
df_cleaned.head(30)

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag,Target
0,20211206_1301,2021-12-06,1301,2982.0,2982.0,2965.0,2971.0,8900,1.0,NaN,False,-0.003263
1,20211206_1332,2021-12-06,1332,592.0,599.0,588.0,589.0,1360800,1.0,NaN,False,-0.008993
2,20211206_1333,2021-12-06,1333,2368.0,2388.0,2360.0,2377.0,125900,1.0,NaN,False,-0.009963
3,20211206_1375,2021-12-06,1375,1230.0,1239.0,1224.0,1224.0,81100,1.0,NaN,False,-0.015032
4,20211206_1376,2021-12-06,1376,1339.0,1372.0,1339.0,1351.0,6200,1.0,NaN,False,0.002867
5,20211206_1377,2021-12-06,1377,3185.0,3215.0,3180.0,3200.0,77000,1.0,NaN,False,0.003044
6,20211206_1379,2021-12-06,1379,1890.0,1898.0,1885.0,1889.0,48500,1.0,NaN,False,-0.009870
7,20211206_1381,2021-12-06,1381,3200.0,3200.0,3150.0,3150.0,1600,1.0,NaN,False,0.000000
8,20211206_1407,2021-12-06,1407,6100.0,6290.0,6010.0,6220.0,246700,1.0,NaN,False,-0.004732
9,20211206_1413,2021-12-06,1413,2185.0,2211.0,2181.0,2190.0,9200,1.0,NaN,False,0.002222
10,20211206_1414,2021-12-06,1414,5090.0,5110.0,5040.0,5060.0,121500,1.0,NaN,False,-0.009728
11,20211206_1417,2021-12-06,1417,2001.0,2019.0,1988.0,1991.0,209200,1.0,NaN,False,-0.010386
12,20211206_1419,2021-12-06,1419,2285.0,2289.0,2253.0,2288.0,123500,1.0,NaN,False,-0.018684
13,20211206_1429,2021-12-06,1429,709.0,714.0,704.0,712.0,33300,1.0,NaN,False,-0.005355
14,20211206_1431,2021-12-06,1431,831.0,862.0,818.0,837.0,43700,1.0,NaN,False,-0.002312
15,20211206_1435,2021-12-06,1435,226.0,227.0,221.0,222.0,209700,1.0,NaN,False,0.008584
16,20211206_1515,2021-12-06,1515,6340.0,6360.0,6240.0,6310.0,12200,1.0,NaN,False,0.003120
17,20211206_1518,2021-12-06,1518,1355.0,1380.0,1331.0,1332.0,453800,1.0,NaN,False,0.016464
18,20211206_1605,2021-12-06,1605,937.0,956.0,937.0,947.0,9554500,1.0,NaN,False,0.015400
19,20211206_1662,2021-12-06,1662,2385.0,2412.0,2361.0,2397.0,292000,1.0,NaN,False,0.030000
20,20211206_1663,2021-12-06,1663,1482.0,1507.0,1456.0,1460.0,30500,1.0,NaN,False,-0.002694
21,20211206_1712,2021-12-06,1712,1663.0,1699.0,1621.0,1647.0,79300,1.0,NaN,False,0.021059
22,20211206_1716,2021-12-06,1716,1336.0,1336.0,1310.0,1312.0,7500,1.0,NaN,False,0.002999
23,20211206_1719,2021-12-06,1719,889.0,897.0,879.0,880.0,825600,1.0,NaN,False,-0.007848
24,20211206_1720,2021-12-06,1720,675.0,678.0,664.0,664.0,330800,1.0,NaN,False,-0.007396
25,20211206_1721,2021-12-06,1721,2520.0,2573.0,2519.0,2558.0,481200,1.0,NaN,False,-0.009150
26,20211206_1726,2021-12-06,1726,353.0,355.0,348.0,349.0,148300,1.0,NaN,False,-0.013736
27,20211206_1762,2021-12-06,1762,1945.0,1952.0,1938.0,1946.0,46200,1.0,NaN,False,-0.003035
28,20211206_1766,2021-12-06,1766,9290.0,9400.0,9160.0,9280.0,12900,1.0,NaN,False,0.004224
29,20211206_1775,2021-12-06,1775,2580.0,2614.0,2580.0,2612.0,700,1.0,NaN,False,0.023274

**While ranking our stock prices Null Values(days where there was no trade of that stock, or any other reason) of open high low close are not as useful so we will drop them**

In [34]:
duplicates=df_cleaned.duplicated()
true_count = duplicates.sum()
print(true_count)
# No duplicates

0

In [35]:
df_cleaned['RowId'].count()

269063

In [36]:
df_cleaned['RowId'].nunique()

269063

Data is cleaned with 
1. No missing values
2. No duplicates
3. Correct datatype for all field (date as datetime, open,high,close etc as float64 and so on)